import type { Metadata } from "next";

// import { CopilotKit } from "@copilotkit/react-core"; // Temporarily disabled
import "./globals.css";
// import "@copilotkit/react-ui/styles.css"; // Temporarily disabled

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={"antialiased"}>
        {/* CopilotKit temporarily disabled during development */}
        {/* <CopilotKit runtimeUrl="/api/copilotkit" agent="sample_agent"> */}
          {children}
        {/* </CopilotKit> */}
      </body>
    </html>
  );
}
